// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDkAfcSxEQXzNQ5FCwgO-DQLtSGvmdDFI',
    appId: '1:64242705145:web:9bdf8b12b57681199ab828',
    messagingSenderId: '64242705145',
    projectId: 'collab-d7999',
    authDomain: 'collab-d7999.firebaseapp.com',
    storageBucket: 'collab-d7999.firebasestorage.app',
    measurementId: 'G-4QMNHWMJK0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcer5kEuToWK6iGX-05QdZefTwljVpYCQ',
    appId: '1:64242705145:android:4374ab7ff0937afd9ab828',
    messagingSenderId: '64242705145',
    projectId: 'collab-d7999',
    storageBucket: 'collab-d7999.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOhEvEVKbBidGXGYAwkX7rhQVY5mgIZ6A',
    appId: '1:64242705145:ios:5e800ea12df475ce9ab828',
    messagingSenderId: '64242705145',
    projectId: 'collab-d7999',
    storageBucket: 'collab-d7999.firebasestorage.app',
    iosBundleId: 'com.example.collab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOhEvEVKbBidGXGYAwkX7rhQVY5mgIZ6A',
    appId: '1:64242705145:ios:5e800ea12df475ce9ab828',
    messagingSenderId: '64242705145',
    projectId: 'collab-d7999',
    storageBucket: 'collab-d7999.firebasestorage.app',
    iosBundleId: 'com.example.collab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDkAfcSxEQXzNQ5FCwgO-DQLtSGvmdDFI',
    appId: '1:64242705145:web:c149471780da3bea9ab828',
    messagingSenderId: '64242705145',
    projectId: 'collab-d7999',
    authDomain: 'collab-d7999.firebaseapp.com',
    storageBucket: 'collab-d7999.firebasestorage.app',
    measurementId: 'G-K4JBTSZNF3',
  );
}
